kind: Service
apiVersion: v1
metadata:
  name: player-service
spec:
  selector:
    app: player-service
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
  labels:
    app: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
      - name: player-service
        image: localhost:5000/player-service:0.0.1-SNAPSHOT
        envFrom:
        - configMapRef:
            name: player-service        
        resources:
          requests:
            memory: "768M"
            cpu: "1"
          limits:
            memory: "768M"
            cpu: "1"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always