
kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres

  ports:
  - port: 10810
    targetPort: 5432



---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgresclaim
        persistentVolumeClaim:
          claimName: postgresclaim
      containers:
      - name: postgres
        image: localhost:5000/postgres:9.5
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        lifecycle:
          preStop:
            exec:
              command: ["su postgres", "-c", "'/usr/pgsql-9.5/bin/pg_ctl -D /opt/pgsql/9.5/data stop'"]          
#        livenessProbe:
#          exec:
#            command:
#              - /bin/sh
#              - -c
#              - /usr/bin/pg_isready -q
#          initialDelaySeconds: 15
#          periodSeconds: 5
#          successThreshold: 1
#          failureThreshold: 3
        volumeMounts:
        - mountPath: "/opt/pgsql/9.5"
          name: postgresclaim


---

